sudo: required

services: docker
language: scala
jdk: oraclejdk8
node_js: 7

script:
    - set -e
    - .travis/build
    - .travis/integration-tests
    - set +e

after_success:
    - set -e
    - .travis/publish-docker
    - sbt coveralls
    - set +e

cache:
  yarn: true
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
