sudo: required

services: docker
language: scala
jdk: oraclejdk8
# node_js: 7

install:
    - set -e # https://github.com/travis-ci/travis-ci/issues/1066#issuecomment-32415710
    - . $HOME/.nvm/nvm.sh
    - nvm install stable
    - nvm use stable
    - npm install
    - npm install jsdom@9.12.0 # newer version seems to make problems
    - set +e

script:
    - set -e
    - .travis/build
    - .travis/integration-tests
    - set +e

after_success:
    - set -e
    - .travis/publish-docker
    - sbt coveralls
    - set +e

cache:
  yarn: true
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
