version: '2'

services:
  postgres:
    stdin_open: true
    tty: true
    image: postgres:9.6.1-alpine
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "dev"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
  db-migration:
    stdin_open: true
    tty: true
    image: woost/wust2.db-migration
    command: -url='jdbc:postgresql://postgres/dev' -schemas=public -user=dev -password=dev migrate
