version: '2'

services:
  postgres:
    extends:
      file: services.yml
      service: postgres
    environment: &pg_env
      POSTGRES_PASSWORD: "test"
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
  db-migration:
    extends:
      file: services.yml
      service: db-migration
    environment:
      <<: *pg_env
    stdin_open: true
    tty: true
    depends_on:
      - postgres
