version: '2'

services:
  postgres:
    restart: on-failure
    extends:
      file: services.yml
      service: postgres
    environment: &pg_env
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
  db-migration:
    restart: on-failure
    extends:
      file: services.yml
      service: db-migration
    environment:
      <<: *pg_env
    depends_on:
      - postgres
  wust:
    restart: on-failure
    extends:
      file: services.yml
      service: wust
    environment:
      <<: *pg_env
      WUST_AUTH_SECRET: "secret"
    depends_on:
      - postgres
  nginx:
    restart: on-failure
    extends:
      file: services.yml
      service: nginx
    volumes:
      - .test_certs:/tls_certs/:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wust
  nginx-http:
    restart: on-failure
    extends:
      file: services.yml
      service: nginx-http
    ports:
      - "80:80"
    depends_on:
      - wust
