version: '2'

services:
  postgres:
    extends:
      file: common-prod.yml
      service: postgres
  db-migration:
    extends:
      file: common-prod.yml
      service: db-migration
    depends_on:
      - postgres
  wust:
    extends:
      file: common-prod.yml
      service: wust
    depends_on:
      - postgres
  nginx:
    extends:
      file: common-prod.yml
      service: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wust
