version: '2'

services:
  postgres:
    extends:
      file: common-test.yml
      service: postgres
  db-migration:
    extends:
      file: common-test.yml
      service: db-migration
    depends_on:
      - postgres
  test:
    image: cornerman/docker-pgtap
    command: -h postgres -u 'wust' -w 'test' -d 'wust'
    volumes:
      - "../dbMigration/tests/:/t"
    depends_on:
      - postgres
