version: '2'

services:
  postgres:
    image: woost/postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pw'
      POSTGRES_DB: 'db'
  test:
    image: cornerman/docker-pgtap
    command: -h postgres -u 'user' -w 'pw' -d 'db'
    depends_on:
      - postgres
    volumes:
      - "../postgres/tests/:/t"
