version: '2'

services:
  postgres:
    extends:
      file: common-test.yml
      service: postgres
  db-migration:
    extends:
      file: common-test.yml
      service: db-migration
    depends_on:
      - postgres
  wust:
    extends:
      file: common-test.yml
      service: wust
    depends_on:
      - postgres
  nginx:
    image: woost/wust2.nginx:http
    environment:
      HOST_DOMAIN: "localhost"
    ports:
      - "80:80"
    depends_on:
      - wust
