version: '2'

services:
  postgres:
    extends:
      file: common-prod.yml
      service: postgres
  db-migration:
    extends:
      file: common-prod.yml
      service: db-migration
    depends_on:
      - postgres
  wust:
    extends:
      file: common-prod.yml
      service: wust
    depends_on:
      - postgres
  nginx:
    image: woost/wust2.nginx:0.1.0-SNAPSHOT
    environment:
      HOST_DOMAIN: ${HOST_DOMAIN}
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wust
    volumes:
      - ${NGINX_VOLUME}:${NGINX_VOLUME}
