version: '2'

services:
  postgres:
    build: ../postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pw'
      POSTGRES_DB: 'db'
  test:
    build:
      context: ../postgres
      dockerfile: Dockerfile.test
    command: -h postgres -u 'user' -w 'pw' -d 'db'
    depends_on:
      - postgres
    volumes:
      - "../postgres/tests/:/t"
