version: '2'

services:
  postgres:
    image: postgres:9.6.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
  db-migration:
    image: woost/db-migration
    command: -url='jdbc:postgresql://postgres/wust' -schemas=public -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    depends_on:
      - postgres
