version: '2'

services:
  postgres:
    extends:
      file: common-dev.yml
      service: postgres
    ports:
      - "5432:5432"
  db-migration:
    extends:
      file: common-dev.yml
      service: db-migration
    depends_on:
      - postgres
