version: '2'

services:
  postgres:
    image: woost/postgres
    environment: &pg_env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "wust"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
  wust:
    image: monostream/openjdk-sbt
    stdin_open: true
    tty: true
    environment:
      <<: *pg_env
      POSTGRES_HOSTNAME: "postgres"
    ports:
      - "8080:8080"
    volumes:
      - ../:/workspace
      - ~/.ivy2/:/root/.ivy2
    depends_on:
      - postgres
